### ISSUE TITLE
Action failing due to unpublished fix for `ovh` -> `zone`

### ISSUE THREAD

**Issue by seleb** [yeslayla/butler-publish-itchio-action#14]
Hey there! I noticed this action started failing recently with the following error:

```sh
  ERROR: failed to solve: process "/bin/sh -c curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default     && unzip butler.zip     && cp butler /usr/bin     && chmod +x /usr/bin/butler" did not complete successfully: exit code: 6
```

It looks like the cause is the `ovh` domain being replaced with `zone` on itch's side (https://github.com/itchio/butler/commit/898b30bb2cadaaf561d91c4f7784aa1927c5cfb2). Although that seems to have been addressed awhile ago in b5f0b072e8b12b731c69f12b5430f594700e0947, this change isn't published as a specific version.

Using the commit hash instead of a version number works, but thought I'd report the issue for visibility.

**Comment by marcmaliar** [comment]
I'm running into the same issue, but it happened TODAY https://itch.io/docs/butler/installing.html not sure why

**Comment by marcmaliar** [comment]
I just raised a PR

Edit: Actually maybe their server is down 

I navigate to https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default and I get "Invalid file requested" right now

**Comment by stratedge** [comment]
EDIT: Spoke too soon, it looks like itch's file server on broth.itch.zone is having some major issues. I can't get a single file to resolve. The server is responding, it's just sending back 404s for every file, which makes me wonder if there's a misconfiguration. It's not just butler, it looks like any file stored there is failing to resolve.

---

It looks like https://broth.itch.zone/butler/linux-amd64/LATEST resolves to a text file that lists the latest tag, which at the moment is 15.24.0.

https://broth.itch.zone/butler/linux-amd64/LATEST/archive resolves with a 404 and https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default resolves with a 404. So it looks like they may not be populating the `/LATEST/archive` resource anymore, or at least not at the moment. If that's true, I guess the thing to do would be to make a GET request to https://broth.itch.zone/butler/linux-amd64/LATEST to get the latest tag value, and then to use that to construct the URL to download the file from.

**Comment by marcmaliar** [comment]
Nah man nothing works: https://github.com/itchio/butler/issues/278#issuecomment-3294039042 there's no workaround like that

**Comment by seleb** [comment]
Quick update for anyone checking this thread for workarounds as this came up again recently: The original workaround using b5f0b072e8b12b731c69f12b5430f594700e0947 still works as expected, and I believe the comments above are all due to unrelated issues (e.g. server stability during a period where itch was being overwhelmed with bot traffic).

Here is a snippet from a workflow of mine which currently uses the action successfully for reference:
```yml
      - uses: yeslayla/butler-publish-itchio-action@b5f0b072e8b12b731c69f12b5430f594700e0947
        env:
          BUTLER_CREDENTIALS: ${{ secrets.ITCH_API_KEY }}
          CHANNEL: web
          ITCH_GAME: ${{ env.ITCH_GAME }}
          ITCH_USER: ${{ env.ITCH_USER }}
          PACKAGE: dist
          VERSION: ${{ steps.package-version.outputs.current-version }}
```
